const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
for (const ext of ['.ts', '.tsx']) require.extensions[ext] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.React } }).outputText, filename)
const { JSDOM } = require('jsdom')
const boot = new JSDOM('<html><body></body></html>')
global.window = boot.window; global.document = boot.window.document
const React = require('react')
const { createRoot } = require('react-dom/client')
const { act } = React
const theme = require('../src/components/ThemeModal.tsx')
const backup = require('../src/utils/backupSettings.ts')
const { exportCustomPaletteJson } = require('../src/utils/customPaletteJson.ts')
boot.window.close()
async function harness(run) {
  const dom = new JSDOM('<html><head></head><body><div id="root"></div></body></html>', { url: 'https://gtar.test' })
  Object.assign(global, { window: dom.window, document: dom.window.document, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true })
  let root = createRoot(document.getElementById('root'))
  let open
  function AppThemeState() {
    const [mode, setMode] = React.useState(() => theme.hydrateThemeSettings().mode)
    const [colors, setColors] = React.useState(() => theme.hydrateThemeSettings().standalone)
    const [isOpen, setOpen] = React.useState(true)
    open = () => act(async () => setOpen(true))
    React.useEffect(() => { theme.applyThemeRuntime(mode, colors) }, [mode, colors])
    return React.createElement(theme.ThemeModal, { isOpen, currentTheme: mode, customColors: colors, onClose: () => setOpen(false), onApplyTheme: (next, palette) => { setMode(next); if (next === 'custom') setColors(palette) } })
  }
  const mount = () => act(async () => root.render(React.createElement(AppThemeState)))
  const reload = async () => { await act(async () => root.unmount()); root = createRoot(document.getElementById('root')); document.documentElement.removeAttribute('style'); await mount() }
  const find = id => document.querySelector(`[data-testid="${id}"]`)
  const click = async id => { assert.ok(find(id), id); await act(async () => find(id).click()) }
  const input = async (selector, value) => { const el = document.querySelector(selector); assert.ok(el, selector); await act(async () => { Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set.call(el, value); el.dispatchEvent(new window.Event('input', { bubbles: true })) }) }
  const stored = key => JSON.parse(localStorage.getItem(backup.SETTINGS_KEYS[key]))
  const bg = () => document.documentElement.style.getPropertyValue('--custom-stage-bg')
  try { await run({ mount, reload, open: () => open(), find, click, input, stored, bg }) } finally { await act(async () => root.unmount()); dom.window.close(); delete global.window; delete global.document; delete global.localStorage; delete global.IS_REACT_ACT_ENVIRONMENT }
}

test('A–I: actual controlled UI edits, Save & Apply, reload, roundtrip, edit again, deletion and independent standalone backup', async () => harness(async ({ mount, reload, open, find, click, input, stored, bg }) => {
  const factorySnapshot = JSON.stringify(theme.THEME_OPTIONS)
  const ids = () => [...document.querySelectorAll('[data-testid^="theme-slot-"]')].map(el => el.dataset.testid)
  await mount()
  const order = ids()
  assert.equal(document.querySelectorAll('[data-testid^="restore-factory-"]').length, 0)
  await click('open-custom-palette-editor-btn')
  await input('[data-testid="color-control-bgHex"] input[type="text"]', '#123456')
  await click('save-apply-palette-btn')
  const standalone = stored('customThemeColors')
  assert.equal(standalone.bgHex, '#123456'); assert.equal(standalone.identity, undefined)
  await open(); await click('theme-slot-paper-light'); await click('theme-save-apply-btn')
  assert.equal(bg(), theme.presetToCustomPalette(theme.THEME_OPTIONS[3]).bgHex)
  await open(); await click('customize-preset-paper-light-btn')
  await input('[data-testid="color-control-bgHex"] input[type="text"]', '#654321')
  await input('[aria-label="Custom theme name"]', '  My Paper  ')
  assert.equal(find('palette-live-preview-box').style.backgroundColor, 'rgb(101, 67, 33)')
  assert.deepEqual(stored('customThemeColors'), standalone, 'preview never consumes standalone state')
  await click('save-apply-palette-btn')
  assert.equal(localStorage.getItem(backup.SETTINGS_KEYS.themeMode), 'paper-light')
  const override = stored('factoryThemeOverrides')['paper-light']
  assert.equal(override.identity.factoryId, 'paper-light'); assert.equal(override.identity.displayName, 'My Paper'); assert.equal(override.bgHex, '#654321')
  assert.deepEqual(stored('customThemeColors'), standalone)
  assert.equal(bg(), '#654321')
  await reload()
  assert.equal(bg(), '#654321'); assert.match(find('theme-slot-paper-light').textContent, /My Paper/)
  assert.ok(find('restore-factory-paper-light')); assert.deepEqual(ids(), order)
  await click('theme-slot-azure-stage'); await click('theme-save-apply-btn')
  await open(); await click('theme-slot-paper-light'); await click('theme-save-apply-btn'); assert.equal(bg(), '#654321')
  await open(); await click('customize-preset-paper-light-btn')
  assert.equal(document.querySelector('[aria-label="Custom theme name"]').value, 'My Paper')
  assert.equal(document.querySelector('[data-testid="color-control-bgHex"] input[type="text"]').value, '#654321')
  await click('cancel-palette-editor-btn')
  await click('custom-theme-option-card'); await click('theme-save-apply-btn'); assert.equal(bg(), '#123456')
  await reload(); assert.equal(bg(), '#123456'); assert.deepEqual(stored('factoryThemeOverrides')['paper-light'], override)
  const payload = backup.readBackupSettings(); localStorage.clear(); backup.restoreBackupSettings(payload); await reload()
  assert.equal(bg(), '#123456'); assert.deepEqual(stored('factoryThemeOverrides')['paper-light'], override)
  await click('theme-slot-paper-light'); await click('restore-factory-paper-light'); await click('confirm-factory-restore')
  assert.deepEqual(stored('factoryThemeOverrides')['paper-light'], override, 'restore waits for selector Save & Apply')
  await click('theme-save-apply-btn')
  assert.deepEqual(stored('factoryThemeOverrides'), {}); assert.deepEqual(stored('customThemeColors'), standalone)
  const defaults = theme.presetToCustomPalette(theme.THEME_OPTIONS[3])
  assert.deepEqual(theme.resolveThemePalette('paper-light', standalone), defaults); assert.equal(bg(), defaults.bgHex)
  await reload(); assert.deepEqual(ids(), order); assert.match(find('theme-slot-paper-light').textContent, /Paper Cream Light/); assert.doesNotMatch(find('theme-slot-paper-light').textContent, /My Paper/); assert.equal(find('restore-factory-paper-light'), null)
  await click('custom-theme-option-card'); await click('theme-save-apply-btn'); assert.equal(bg(), '#123456')
  assert.equal(JSON.stringify(theme.THEME_OPTIONS), factorySnapshot)
  assert.equal(document.body.className, 'theme-custom')
  const css = fs.readFileSync(require.resolve('../src/index.css'), 'utf8')
  for (const preset of theme.THEME_OPTIONS) assert.ok(!css.includes(`body.theme-${preset.id}`))
}))

test('Legacy DEV.3j storage upgrades to exact slot plus retained standalone; migration is idempotent', async () => harness(async ({ mount, reload, stored, bg }) => {
  const standalone = theme.normalizeCustomThemeColors({ bgHex: '#ABCDEF' })
  const factory = { ...theme.presetToCustomPalette(theme.THEME_OPTIONS[4]), bgHex: '#FEDCBA', identity: { factoryId: 'crimson-stage', displayName: 'Legacy Crimson' } }
  localStorage.setItem('gtar_standalone_custom_theme_colors', JSON.stringify(standalone))
  localStorage.setItem(backup.SETTINGS_KEYS.customThemeColors, JSON.stringify(factory))
  localStorage.setItem(backup.SETTINGS_KEYS.themeMode, 'custom')
  await mount(); assert.equal(bg(), '#FEDCBA'); assert.equal(localStorage.getItem(backup.SETTINGS_KEYS.themeMode), 'crimson-stage'); assert.deepEqual(stored('customThemeColors'), standalone)
  assert.deepEqual(stored('factoryThemeOverrides')['crimson-stage'], theme.normalizeCustomThemeColors(factory))
  const snapshot = Object.entries(localStorage); await reload(); assert.deepEqual(Object.entries(localStorage), snapshot)
}))

test('JSON color import cannot remove or redirect factory slot identity', async () => harness(async ({ mount, click, input, stored }) => {
  await mount(); await click('customize-preset-paper-light-btn')
  await input('[aria-label="Custom theme name"]', 'Paper Import')
  await click('import-palette-btn')
  const payload = exportCustomPaletteJson({ ...theme.DEFAULT_CUSTOM_COLORS, bgHex: '#112233', identity: { factoryId: 'azure-stage', displayName: 'Wrong Slot' } })
  const el = document.querySelector('[data-testid="palette-json-textarea"]')
  await act(async () => { Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set.call(el, JSON.stringify(payload)); el.dispatchEvent(new window.Event('input', { bubbles: true })) })
  await click('apply-import-json-btn')
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 850)) })
  assert.equal(document.querySelector('[aria-label="Custom theme name"]').value, 'Paper Import')
  await click('save-apply-palette-btn')
  assert.equal(localStorage.getItem(backup.SETTINGS_KEYS.themeMode), 'paper-light')
  assert.equal(stored('factoryThemeOverrides')['paper-light'].bgHex, '#112233')
  assert.equal(stored('factoryThemeOverrides')['paper-light'].identity.factoryId, 'paper-light')
  assert.equal(stored('factoryThemeOverrides')['azure-stage'], undefined)
}))
